ActionMailer::Base.delivery_method = :smtp
ActionMailer::Base.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => 'betafisha.com',
  :user_name            => 'no_reply@betafisha.com',
  :password             => 'rY<FMR7U', 
  :authentication       => 'plain',
  :enable_starttls_auto => true  } 