urls:
- 'http://xml.gamebookers.com/sports/football.xml_attr.xml'
- 'http://xml.gamebookers.com/sports/basketball.xml_attr.xml'
- 'http://xml.gamebookers.com/sports/tennis.xml_attr.xml'
- 'http://xml.gamebookers.com/sports/ice_hockey.xml_attr.xml'
sport:
- sport['name']